from .login_form import LoginForm
from .signup_form import SignUpForm
from .comment_form import CommentForm
from .likedislike_form import LikeDislikeForm
from .map_form import MapForm
from .post_form import PostForm
from .profile_form import ProfileForm
from .team_suggestion_form import TeamSuggestionForm
from .postedmap_form import PostedMapForm
