"""empty message

Revision ID: 37af10713f60
Revises: e5f5da639d8c
Create Date: 2023-02-23 21:44:35.264117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37af10713f60'
down_revision = 'e5f5da639d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teamsuggestions', type_='foreignkey')
    op.create_foreign_key(None, 'teamsuggestions', 'characters', ['character_id'], ['api_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teamsuggestions', type_='foreignkey')
    op.create_foreign_key(None, 'teamsuggestions', 'characters', ['character_id'], ['id'])
    # ### end Alembic commands ###
